name: Auto Merge Markdown PRs

on:
  pull_request:
    branches:
      - seasons-source

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Auto Merge Pull Request
        uses: KeisukeYamashita/auto-pull-request-merge@v1.0.6
        with:
          token: ${{ secrets.GH_TOKEN }}  # از توکن تعبیه شده GitHub استفاده می‌کنیم
          pullRequestNumber: ${{ github.event.pull_request.number }}
          repository: ${{ github.repository }}
          strategy: squash  # روش مرج را squash قرار داده‌ایم
          checkStatus: true  # بررسی وضعیت‌ها قبل از مرج فعال است
          labels: "automerge"  # برچسبی که درخواست‌های مرج اتوماتیک را مشخص می‌کند

