name: Demo to create automatic PR

on:
  push:
    branches:
      - seasons-source

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        id: commit-data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Raise PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "auto-per-branch"
          base: seasons-source
          title: "Auto PR"
          committer: ${{ steps.commit-data.outputs.author_name }} <${{ steps.commit-data.outputs.author_email }}>
          author: ${{ steps.commit-data.outputs.author_name }} <${{ steps.commit-data.outputs.author_email }}>
          body: |
            This is to show automatic PR creation
          token: ${{ secrets.GH_TOKEN }}
          delete-branch: true

      - name: Print PR number
        run: echo "PR number is ${{ steps.create-pr.outputs.pull-request-number }}"

      - name: Approve Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}

      - name: Merge Pull Request
        if: steps.create-pr.outputs.pull-request-number != ''
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          number: ${{ steps.create-pr.outputs.pull-request-number }}
          method: squash
