name: Auto Merge Markdown PRs

on:
  pull_request:
    branches:
      - seasons-source

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check for non-Markdown files
      run: |
        non_md_files=$(git diff --name-only HEAD^ HEAD | grep -v '\.md$' || true)
        if [ -n "$non_md_files" ]; then
          echo "Non-Markdown files detected:"
          echo "$non_md_files"
          exit 1
        fi

    - name: Merge PR
      if: success()
      uses: actions/github-script@v3
      with:
        script: |
          github.pulls.merge({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            merge_method: 'squash'
          })
