name: Auto Merge Markdown PRs

on:
  pull_request:
    branches:
      - seasons-source

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check for non-Markdown files
      run: |
        non_md_files=$(git diff --name-only HEAD^ HEAD | grep -v '\.md$' || true)
        if [ -n "$non_md_files" ]; then
          echo "Non-Markdown files detected:"
          echo "$non_md_files"
          exit 1
        fi

    - name: Merge PR
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        pr_number=$(jq -r .number < "$GITHUB_EVENT_PATH")
        curl -s -X PUT -H "Authorization: token $GITHUB_TOKEN" \
             -H "Accept: application/vnd.github.v3+json" \
             "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/merge" \
             -d '{"merge_method":"squash"}'
