name: Markdown Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Markdown files
        uses: markdownlint/check-action@v0.3.0
        with:
          config_file: .markdownlint.yml  # فایل پیکربندی MarkdownLint اختیاری است

      - name: Report status
        run: echo "Markdown lint check complete"

