name: Status Check

on:
  push:
    branches:
      - seasons-source
  pull_request:
    branches:
      - seasons-source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a simple build check
      run: echo "Build successful!"
